name: Docker Image Build

on:
  pull_request:
    branches:
    - rewrite

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:         
        docker build . --file WebApp.Dockerfile --tag crjekadeveus.azurecr.io/theochat:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER
      
